# Generated by Django 5.0.1 on 2026-06-17 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0012_add_semester_summary_upload_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Session identifier (e.g. 2023/2024)', max_length=20, unique=True)),
                ('is_current', models.BooleanField(default=False, help_text='True for the active session; only one session should be current')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'db_table': 'core_academic_sessions',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester')], help_text='Semester of registration', max_length=10)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('dropped', 'Dropped'), ('carried_over', 'Carried Over')], db_index=True, default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Official course from Academic Core', on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='academics.course')),
                ('session', models.ForeignKey(help_text='Academic session for this registration', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.academicsession')),
                ('student', models.ForeignKey(help_text='The registered student (from Academic Core)', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Course Registration',
                'verbose_name_plural': 'Student Course Registrations',
                'db_table': 'core_student_registrations',
                'ordering': ['-session__name', 'semester', 'student__student_id'],
                'indexes': [models.Index(fields=['student', 'session'], name='core_studen_student_bdf716_idx'), models.Index(fields=['course', 'session', 'semester'], name='core_studen_course__2c1e4e_idx')],
                'unique_together': {('student', 'course', 'session', 'semester')},
            },
        ),
    ]
