# Generated by Django 5.0.1 on 2026-06-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platformbranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformbranding',
            name='dashboard_banner_data',
            field=models.TextField(blank=True, help_text='Cloudinary HTTPS URL for dashboard banner'),
        ),
        migrations.AlterField(
            model_name='platformbranding',
            name='login_background_data',
            field=models.TextField(blank=True, help_text='Cloudinary HTTPS URL for login hero'),
        ),
        migrations.AlterField(
            model_name='platformbranding',
            name='logo_data',
            field=models.TextField(blank=True, help_text='Cloudinary HTTPS URL for logo'),
        ),
    ]
