# Generated by Django 5.0.1 on 2026-01-29 13:24

import common.validators.student_id_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email address (used for admin/HOD/Examiner login)', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, help_text='Student ID in format: U22/FNS/CSC/XXXX (required only for STUDENT role)', max_length=20, null=True, unique=True, validators=[common.validators.student_id_validator.validate_student_id_format]),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
    ]
