# Generated by Django 5.0.1 on 2026-02-03 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True, help_text='If True, user must reset password before accessing dashboard'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('FIRST_LOGIN_PASSWORD_CHANGE', 'First-login password change'), ('PASSWORD_RESET_REQUEST', 'Password reset requested'), ('PASSWORD_RESET_CONFIRM', 'Password reset confirmed'), ('ADMIN_USER_IMPORT', 'Admin user import (CSV/Excel)'), ('ADMIN_ACTION', 'Admin action')], db_index=True, max_length=50)),
                ('identifier', models.CharField(blank=True, help_text='Reg number/email used for login or reset (for failed login or no user)', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Extra context (e.g. count imported)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for failed login or reset request)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
