# Generated by Django 5.0.1 on 2026-02-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_is_first_login_and_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department (e.g. Computer Science); read-only for students', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='True when student has verified email (future-ready)'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, help_text='When password was last changed (settings or reset)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, help_text='Level/Programme (e.g. 300, 400); read-only for students', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('FIRST_LOGIN_PASSWORD_CHANGE', 'First-login password change'), ('PASSWORD_RESET_REQUEST', 'Password reset requested'), ('PASSWORD_RESET_CONFIRM', 'Password reset confirmed'), ('ADMIN_USER_IMPORT', 'Admin user import (CSV/Excel)'), ('ADMIN_ACTION', 'Admin action'), ('PASSWORD_CHANGE', 'Password change (settings)'), ('ADMIN_PASSWORD_RESET', 'Admin password reset'), ('ADMIN_ACTIVATE_DEACTIVATE', 'Admin activate/deactivate user'), ('EMAIL_UPDATED', 'Email updated (settings)')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Email (optional for students; used for admin/HOD login and password reset)', max_length=254, null=True, unique=True),
        ),
    ]
