# Generated by Django 5.0.1 on 2026-02-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_enterprise_course_assignment_and_batch_progress'),
        ('accounts', '0004_student_settings_and_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField(help_text='Original audit_log id')),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('identifier', models.CharField(blank=True, max_length=255)),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('scope_faculty_id', models.PositiveIntegerField(blank=True, null=True)),
                ('scope_department_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit log deletion (archive)',
                'verbose_name_plural': 'Audit log deletions (archive)',
                'db_table': 'audit_log_deletions',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='UsersAccountsHub',
            fields=[
            ],
            options={
                'verbose_name': 'Users / Accounts',
                'verbose_name_plural': 'Users / Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.auditlog',),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_role',
            field=models.CharField(blank=True, help_text='Role of the actor at time of action (SUPER_ADMIN, FACULTY_ADMIN, etc.)', max_length=30),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='scope_department',
            field=models.ForeignKey(blank=True, help_text='Department scope of the action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='academics.department'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='scope_faculty',
            field=models.ForeignKey(blank=True, help_text='Faculty scope of the action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='user',
            name='department_fk',
            field=models.ForeignKey(blank=True, help_text='Department scope (for DEPARTMENT_ADMIN/HOD)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academics.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Faculty scope (for FACULTY_ADMIN)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academics.faculty'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('FIRST_LOGIN_PASSWORD_CHANGE', 'First-login password change'), ('PASSWORD_RESET_REQUEST', 'Password reset requested'), ('PASSWORD_RESET_CONFIRM', 'Password reset confirmed'), ('ADMIN_USER_IMPORT', 'Admin user import (CSV/Excel)'), ('ADMIN_ACTION', 'Admin action'), ('PASSWORD_CHANGE', 'Password change (settings)'), ('ADMIN_PASSWORD_RESET', 'Admin password reset'), ('ADMIN_ACTIVATE_DEACTIVATE', 'Admin activate/deactivate user'), ('EMAIL_UPDATED', 'Email updated (settings)'), ('RESULT_UPLOAD_STARTED', 'Result upload started'), ('RESULT_UPLOAD_COMPLETED', 'Result upload completed'), ('RESULT_BATCH_APPROVED', 'Course batch approved by HOD'), ('RESULT_BATCH_REJECTED', 'Course batch rejected'), ('RESULT_SINGLE_APPROVED', 'Single result approved'), ('RESULT_SINGLE_REJECTED', 'Single result rejected'), ('RESULT_CREATED', 'Result created'), ('RESULT_UPDATED', 'Result updated'), ('RESULT_DELETED', 'Result deleted'), ('RESULT_MANUAL_ENTRY', 'Manual result entry'), ('RESULT_IMPORT_REPORT_DOWNLOAD', 'Import report downloaded')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Extra context / meta (e.g. count imported)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department display (e.g. Computer Science); for students/display', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin (ICT/Registrar)'), ('FACULTY_ADMIN', 'Faculty Admin (Dean)'), ('DEPARTMENT_ADMIN', 'Department Admin (HOD)'), ('EXAMINER', 'Examiner (Lecturer)'), ('STUDENT', 'Student'), ('HOD', 'Head of Department (legacy)')], default='STUDENT', help_text='Enterprise role: Super Admin, Faculty Admin, Department Admin, Examiner, Student', max_length=30),
        ),
    ]
