# Generated by Django 5.0.1 on 2026-02-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_enhance_hod_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_user_scoped', 'Can view users within scope'), ('add_user_scoped', 'Can add users within scope'), ('change_user_scoped', 'Can change users within scope'), ('bulk_import_users', 'Can bulk import users (CSV/Excel)')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('FIRST_LOGIN_PASSWORD_CHANGE', 'First-login password change'), ('PASSWORD_RESET_REQUEST', 'Password reset requested'), ('PASSWORD_RESET_CONFIRM', 'Password reset confirmed'), ('ADMIN_USER_IMPORT', 'Admin user import (CSV/Excel)'), ('ADMIN_ACTION', 'Admin action'), ('PASSWORD_CHANGE', 'Password change (settings)'), ('ADMIN_PASSWORD_RESET', 'Admin password reset'), ('ADMIN_ACTIVATE_DEACTIVATE', 'Admin activate/deactivate user'), ('EMAIL_UPDATED', 'Email updated (settings)'), ('RESULT_UPLOAD_STARTED', 'Result upload started'), ('RESULT_UPLOAD_COMPLETED', 'Result upload completed'), ('RESULT_BATCH_APPROVED', 'Course batch approved by HOD'), ('RESULT_BATCH_REJECTED', 'Course batch rejected'), ('RESULT_SINGLE_APPROVED', 'Single result approved'), ('RESULT_SINGLE_REJECTED', 'Single result rejected'), ('RESULT_CREATED', 'Result created'), ('RESULT_UPDATED', 'Result updated'), ('RESULT_DELETED', 'Result deleted'), ('RESULT_MANUAL_ENTRY', 'Manual result entry'), ('RESULT_IMPORT_REPORT_DOWNLOAD', 'Import report downloaded'), ('AUDIT_LOG_DELETED', 'Audit log deleted (archived)'), ('LOCKED_PUBLISHED', 'Result locked and published'), ('EMERGENCY_UNLOCK', 'Emergency unlock by SuperAdmin')], db_index=True, max_length=50),
        ),
    ]
