# Generated by Django 5.0.1 on 2026-06-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_user_management_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='module_access',
            field=models.JSONField(blank=True, default=list, help_text='Platform modules accessible: results, learning, admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number (optional)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_key',
            field=models.CharField(blank=True, help_text='S3 key for profile picture', max_length=500),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('FIRST_LOGIN_PASSWORD_CHANGE', 'First-login password change'), ('PASSWORD_RESET_REQUEST', 'Password reset requested'), ('PASSWORD_RESET_CONFIRM', 'Password reset confirmed'), ('ADMIN_USER_IMPORT', 'Admin user import (CSV/Excel)'), ('ADMIN_ACTION', 'Admin action'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('PASSWORD_CHANGE', 'Password change (settings)'), ('ADMIN_PASSWORD_RESET', 'Admin password reset'), ('ADMIN_ACTIVATE_DEACTIVATE', 'Admin activate/deactivate user'), ('EMAIL_UPDATED', 'Email updated (settings)'), ('RESULT_UPLOAD_STARTED', 'Result upload started'), ('RESULT_UPLOAD_COMPLETED', 'Result upload completed'), ('RESULT_BATCH_APPROVED', 'Course batch approved by HOD'), ('RESULT_BATCH_REJECTED', 'Course batch rejected'), ('RESULT_BATCH_UNAPPROVED', 'Batch unapproved (reverted to draft)'), ('RESULT_BATCH_REOPENED', 'Rejected batch re-opened for approval'), ('RESULT_SINGLE_APPROVED', 'Single result approved'), ('RESULT_SINGLE_REJECTED', 'Single result rejected'), ('RESULT_CREATED', 'Result created'), ('RESULT_UPDATED', 'Result updated'), ('RESULT_DELETED', 'Result deleted'), ('RESULT_MANUAL_ENTRY', 'Manual result entry'), ('RESULT_IMPORT_REPORT_DOWNLOAD', 'Import report downloaded'), ('AUDIT_LOG_DELETED', 'Audit log deleted (archived)'), ('LOCKED_PUBLISHED', 'Result locked and published'), ('EMERGENCY_UNLOCK', 'Emergency unlock by SuperAdmin'), ('COURSE_CREATED', 'Course created'), ('COURSE_UPDATED', 'Course updated'), ('COURSE_DELETED', 'Course deleted'), ('COURSE_ASSIGNMENT_CREATED', 'Course assignment created'), ('COURSE_ASSIGNMENT_UPDATED', 'Course assignments updated'), ('COURSE_ASSIGNMENT_DELETED', 'Course assignment deleted')], db_index=True, max_length=50),
        ),
    ]
