# Generated by Django 5.0.1 on 2026-06-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_staffinvitation_student_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffinvitation',
            new_name='staff_invit_email_5b8564_idx',
            old_name='staff_invit_email_status_idx',
        ),
        migrations.RenameIndex(
            model_name='staffinvitation',
            new_name='staff_invit_role_0ddd46_idx',
            old_name='staff_invit_role_status_idx',
        ),
    ]
