# Generated by Django 6.0.1 on 2026-01-30 09:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Course code (e.g., CSC201)', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Course title', max_length=200)),
                ('credit_units', models.PositiveIntegerField(help_text='Number of credit units (1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('semester', models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester')], help_text='Semester offered', max_length=20)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level')], help_text='Student level', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Is course currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('gpa', models.DecimalField(decimal_places=2, help_text='Semester GPA', max_digits=3)),
                ('cgpa', models.DecimalField(decimal_places=2, help_text='Cumulative GPA', max_digits=3)),
                ('total_credits', models.PositiveIntegerField(help_text='Total credit units earned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpa_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GPA Record',
                'verbose_name_plural': 'GPA Records',
                'ordering': ['-created_at'],
                'permissions': [('calculate_gpa', 'Can calculate GPA/CGPA')],
                'unique_together': {('student', 'session', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score out of 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(blank=True, choices=[('A', 'A (70-100) - Excellent'), ('B', 'B (60-69) - Very Good'), ('C', 'C (50-59) - Good'), ('D', 'D (45-49) - Fair'), ('E', 'E (40-44) - Pass'), ('F', 'F (0-39) - Fail')], help_text='Calculated grade based on score', max_length=1)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, help_text='Grade point (0-5)', max_digits=3, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved by HOD'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Approval status', max_length=20)),
                ('session', models.CharField(help_text='Academic session (e.g., 2023/2024)', max_length=20)),
                ('semester', models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester')], help_text='Semester', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='HOD who approved this result', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_results', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(help_text='Course for this result', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.course')),
                ('student', models.ForeignKey(help_text='Student who owns this result', on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(help_text='Examiner who uploaded this result', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'ordering': ['-created_at'],
                'permissions': [('upload_result', 'Can upload student results'), ('approve_result', 'Can approve results (HOD only)'), ('view_all_results', 'Can view all students results'), ('view_own_result', 'Can view own results (Student)')],
                'unique_together': {('student', 'course', 'session', 'semester')},
            },
        ),
    ]
