# Generated by Django 6.0.1 on 2026-02-03 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(help_text='Academic session', max_length=20)),
                ('semester', models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester')], help_text='Semester', max_length=20)),
                ('le', models.CharField(blank=True, help_text='LE', max_length=50)),
                ('nss', models.CharField(blank=True, help_text='NSS', max_length=50)),
                ('rcu', models.CharField(blank=True, help_text='RCU', max_length=50)),
                ('ecu', models.CharField(blank=True, help_text='ECU', max_length=50)),
                ('cp', models.CharField(blank=True, help_text='CP', max_length=50)),
                ('gpa', models.CharField(blank=True, help_text='GPA', max_length=50)),
                ('trcu', models.CharField(blank=True, help_text='TRCU', max_length=50)),
                ('tecu', models.CharField(blank=True, help_text='TECU', max_length=50)),
                ('tcp', models.CharField(blank=True, help_text='TCP', max_length=50)),
                ('pcgpa', models.CharField(blank=True, help_text='PCGPA', max_length=50)),
                ('cgpa', models.CharField(blank=True, help_text='CGPA', max_length=50)),
                ('standing', models.CharField(blank=True, help_text='Standing', max_length=50)),
                ('raw_summary', models.TextField(blank=True, help_text='Raw summary string as uploaded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='semester_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semester Summary',
                'verbose_name_plural': 'Semester Summaries',
                'ordering': ['-session', '-semester'],
                'unique_together': {('student', 'session', 'semester')},
            },
        ),
    ]
