# Generated by Django 5.0.1 on 2026-02-04 18:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_result_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Faculty code (e.g. FNS)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Faculty name', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Department code (e.g. CSC)', max_length=20)),
                ('name', models.CharField(help_text='Department name', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='Parent faculty', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.faculty')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['faculty', 'code'],
                'unique_together': {('faculty', 'code')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department that owns this course (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.department'),
        ),
        migrations.CreateModel(
            name='ResultUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original file name', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('session', models.CharField(blank=True, help_text='Session from upload', max_length=20)),
                ('semester', models.CharField(blank=True, help_text='Semester from upload', max_length=20)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department scope (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_upload_batches', to='academics.department')),
                ('faculty', models.ForeignKey(blank=True, help_text='Faculty scope (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_upload_batches', to='academics.faculty')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Result upload batch',
                'verbose_name_plural': 'Result upload batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_index=True, max_length=20)),
                ('semester', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED_BY_HOD', 'Approved by HOD'), ('REJECTED', 'Rejected'), ('REOPEN', 'Request changes'), ('PUBLISHED', 'Published')], db_index=True, default='PENDING', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_course_batches', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(help_text='Course for this batch', on_delete=django.db.models.deletion.CASCADE, related_name='course_batches', to='academics.course')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_course_batches', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_batches', to='academics.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_batches', to='academics.faculty')),
            ],
            options={
                'verbose_name': 'Course batch',
                'verbose_name_plural': 'Course batches',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'session', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='ResultRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(help_text='1-based line number in file')),
                ('reg_number', models.CharField(blank=True, max_length=50)),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('session', models.CharField(blank=True, max_length=20)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ATTACHED', 'Attached'), ('ERROR', 'Error')], db_index=True, default='ERROR', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('result', models.ForeignKey(blank=True, help_text='Created Result when status=ATTACHED', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_rows', to='academics.result')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='academics.resultuploadbatch')),
            ],
            options={
                'verbose_name': 'Result upload row',
                'verbose_name_plural': 'Result upload rows',
                'ordering': ['batch', 'line_no'],
                'unique_together': {('batch', 'line_no')},
            },
        ),
    ]
