# Generated by Django 5.0.1 on 2026-02-04 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_add_faculty_department_batch_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultuploadbatch',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Number of rows processed (for background uploads)'),
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(help_text='Course the examiner can view results for', on_delete=django.db.models.deletion.CASCADE, related_name='examiner_assignments', to='academics.course')),
                ('examiner', models.ForeignKey(help_text='Examiner (lecturer) with view-only access to this course', limit_choices_to={'role': 'EXAMINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course assignment',
                'verbose_name_plural': 'Course assignments',
                'ordering': ['course__code', 'examiner__email'],
                'unique_together': {('examiner', 'course')},
            },
        ),
    ]
