# Generated by Django 5.0.1 on 2026-02-05 16:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_result_is_editable'),
        ('accounts', '0007_enhance_hod_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA256 checksum for tamper detection', max_length=64),
        ),
        migrations.AddField(
            model_name='result',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department scope', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='academics.department'),
        ),
        migrations.AddField(
            model_name='result',
            name='faculty_reviewer_remark',
            field=models.TextField(blank=True, help_text='Remarks from Faculty Reviewer (if applicable)'),
        ),
        migrations.AddField(
            model_name='result',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When result was locked (LOCKED_PUBLISHED status)', null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='User who locked this result', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if status=REJECTED)'),
        ),
        migrations.AddField(
            model_name='result',
            name='upload_batch',
            field=models.ForeignKey(blank=True, help_text='Upload batch this result belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='academics.resultuploadbatch'),
        ),
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FACULTY_REVIEW', 'Faculty Review'), ('HOD_REVIEW', 'HOD Review'), ('APPROVED', 'Approved by HOD'), ('LOCKED_PUBLISHED', 'Locked & Published'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for Revision')], default='DRAFT', help_text='Workflow status', max_length=30),
        ),
        migrations.CreateModel(
            name='AuditForwardingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarding_type', models.CharField(choices=[('WEBHOOK', 'Webhook'), ('EMAIL', 'Email'), ('DAILY_DIGEST', 'Daily Digest')], help_text='Type of forwarding', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20)),
                ('endpoint_url', models.CharField(blank=True, help_text='Webhook endpoint URL', max_length=500)),
                ('payload', models.JSONField(default=dict, help_text='Forwarded payload')),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('audit_log', models.ForeignKey(help_text='Audit log being forwarded', on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_logs', to='accounts.auditlog')),
            ],
            options={
                'verbose_name': 'Audit forwarding log',
                'verbose_name_plural': 'Audit forwarding logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Version number (1, 2, 3...)')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(max_length=1)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('change_reason', models.TextField(blank=True, help_text='Reason for change (required for emergency unlock)')),
                ('checksum', models.CharField(help_text='SHA256 checksum of this version for tamper detection', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_versions_created', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(help_text='Parent result', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='academics.result')),
            ],
            options={
                'verbose_name': 'Result version',
                'verbose_name_plural': 'Result versions',
                'ordering': ['-version_number'],
                'unique_together': {('result', 'version_number')},
            },
        ),
    ]
