# Generated by Django 5.0.1 on 2026-03-07 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_add_outstanding_remarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='semestersummary',
            name='approved',
            field=models.BooleanField(default=False, help_text='Summary approved by HOD'),
        ),
        migrations.AddField(
            model_name='semestersummary',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestersummary',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this summary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_semester_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A (70-100) - Excellent'), ('B', 'B (60-69) - Very Good'), ('C', 'C (50-59) - Good'), ('D', 'D (45-49) - Fair'), ('E', 'E (40-44) - Pass'), ('F', 'F (0-39) - Fail')], help_text='Grade as uploaded; no auto-calculation', max_length=1),
        ),
    ]
