# Generated by Django 5.0.1 on 2026-03-09 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_add_semester_summary_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestersummary',
            name='upload_batch',
            field=models.ForeignKey(blank=True, help_text='Upload batch this summary came from (empty if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_summaries', to='academics.resultuploadbatch'),
        ),
    ]
